/**
 * One-off script to generate word lists for the title generator.
 * Pulls random words from WordNet via wordpos, prints them as TypeScript arrays.
 * Run with: npx tsx scripts/generate-word-lists.ts
 * Then copy the output into src/client/plant/titleWords.ts and curate.
 */

import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const WordPos = require('wordpos')

const wordpos = new WordPos()

const COUNT = 300

const unique = (arr: string[]): string[] => [...new Set(arr)]

const fetchWords = async (
  method: string,
  count: number,
): Promise<string[]> => {
  const results: string[] = []
  while (results.length < count) {
    const batch: string[] = await wordpos[method](
      Math.min(50, count - results.length),
    )
    results.push(...batch)
    if (batch.length === 0) break
  }
  return unique(results).slice(0, count)
}

const formatArray = (name: string, words: string[]): string => {
  const sorted = [...words].sort()
  const items = sorted.map(w => `  '${w}'`).join(',\n')
  return `export const ${name} = [\n${items},\n]`
}

const run = async (): Promise<void> => {
  console.error('Fetching nouns...')
  const nouns = await fetchWords('randNoun', COUNT)
  console.error('Fetching verbs...')
  const verbs = await fetchWords('randVerb', COUNT)
  console.error('Fetching adjectives...')
  const adjectives = await fetchWords('randAdjective', COUNT)

  console.log('// Auto-generated by scripts/generate-word-lists.ts')
  console.log('// Review and curate before committing.\n')
  console.log(formatArray('NOUNS', nouns))
  console.log()
  console.log(formatArray('VERBS', verbs))
  console.log()
  console.log(formatArray('ADJECTIVES', adjectives))
}

run().catch(err => {
  console.error(err)
  process.exit(1)
})
