/**
 * Seed the database with songs. Titles are auto-generated by the server.
 *
 * Requires the app to be running: yarn dev
 *
 * Usage:
 *   tsx scripts/seed-songs.ts
 *   tsx scripts/seed-songs.ts --count 10
 */

import { z } from 'zod';

const BASE_URL = 'http://localhost:3000/trpc';
const DEFAULT_COUNT = 20;

const GROWTH_STAGES = [
  'seed',
  'seedling',
  'sprout',
  'budding',
  'blooming',
  'dormant',
] as const;

const BODY_LINES = [
  'Melody in D minor, needs a bridge.',
  'Rough idea — came to me on the bus.',
  'Could be a duet. Try with fingerpicking.',
  '90bpm, 4/4. Verse needs work.',
  'Sample the rain from yesterday.',
  'Starts quiet, builds to something big.',
  'Folk feel, maybe a banjo.',
  'Needs a proper chorus. Placeholder for now.',
  'Ambient, no drums. Lots of reverb.',
  'Upbeat. Think summer, late afternoon.',
  '',
  '',
  '',
];

const pickRandom = <T>(arr: readonly T[]): T =>
  arr[Math.floor(Math.random() * arr.length)];

const CreateResponseSchema = z.object({
  result: z.object({ data: z.object({ id: z.string(), title: z.string() }) }),
});

const createSong = async (body: string, growthStage: string): Promise<string> => {
  const createResponse = await fetch(`${BASE_URL}/song.create`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ body }),
  });

  if (!createResponse.ok) {
    const text = await createResponse.text();
    throw new Error(`Failed to create song: ${createResponse.status} ${text}`);
  }

  const created = CreateResponseSchema.parse(await createResponse.json());
  const { id, title } = created.result.data;

  if (growthStage !== 'seed') {
    const updateResponse = await fetch(`${BASE_URL}/song.update`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id, growth_stage: growthStage }),
    });

    if (!updateResponse.ok) {
      const text = await updateResponse.text();
      throw new Error(`Created "${title}" but failed to set stage: ${updateResponse.status} ${text}`);
    }
  }

  return title;
};

const main = async (): Promise<void> => {
  const countArg = process.argv.indexOf('--count');
  const count = countArg !== -1 ? parseInt(process.argv[countArg + 1], 10) : DEFAULT_COUNT;

  if (isNaN(count) || count < 1) {
    console.error('--count must be a positive integer');
    process.exit(1);
  }

  console.log(`Seeding ${count} songs...`);

  let created = 0;
  while (created < count) {
    const body = pickRandom(BODY_LINES);
    const stage = pickRandom(GROWTH_STAGES);
    try {
      const title = await createSong(body, stage);
      console.log(`  [${created + 1}/${count}] "${title}" (${stage})`);
      created++;
    } catch (err) {
      console.error(`  Error: ${err}`);
    }
  }

  console.log(`\nDone. Created ${created} song(s).`);
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
